### ISSUE TITLE
Rotation logic can fail in some cases when OLD_SECRET_KEY is missing

### ISSUE THREAD

**Issue by Namingwaysway** [EralpB/django-rotate-secret-key#1]
For auth situations, I'm hitting the following line after rotating off of the OLD_SECRET_KEY, and the entry is no longer in settings.  If this session is "valid", but the rotation key is no longer there, we should likely force the user to reauth

salted_hmac(key_salt, user.password, secret=settings.OLD_SECRET_KEY).hexdigest()

**Comment by EralpB** [comment]
Fixed with the PR.
